### ISSUE TITLE
Adding it to OpenWrt LuCI repository

### ISSUE THREAD

**Issue by BKPepe** [4IceG/luci-app-3ginfo#1]
Hi,

Do you have any plans to contribute it to [OpenWrt's LuCI repository](https://github.com/openwrt/luci)? I would like to see it there. Currently, there is no GUI to have information about LTE connection such as signal strength and so on. Also, you would not need to provide compiled binaries as users can just do opkg update and opkg install and it will be download from OpenWrt repositories.

**Comment by 4IceG** [comment]
Hi,
I haven't thought about adding my package / packages to the repository. I know that there weren't many useful things in Openwrt for mobile internet users, that's probably why I added some things better or worse, shared on my github.

**Comment by 4IceG** [comment]
> 
> 
> Hi,
> 
> Do you have any plans to contribute it to [OpenWrt's LuCI repository](https://github.com/openwrt/luci)? I would like to see it there. Currently, there is no GUI to have information about LTE connection such as signal strength and so on. Also, you would not need to provide compiled binaries as users can just do opkg update and opkg install and it will be download from OpenWrt repositories.

Hi BKPepe,

This idea of adding my packages to the repo is valid because I would be for it .. lately I get a lot of requests for compilation for various devices.
