### ISSUE TITLE
opkg install luci-app-3ginfo_1.3_all.ipk 

### ISSUE THREAD

**Issue by salchris** [4IceG/luci-app-3ginfo#3]
Hi, i downloaded everything but i think there's no IPK for opkg install luci-app-3ginfo_1.3_all.ipk
Thank you

**Comment by 4IceG** [comment]
Hi, All files are enough to look for (https://github.com/4IceG/luci-app-3ginfo/releases). I don't know what modem you have, but install 3ginfo-text_20171227_all.ipk + luci-app-3ginfo_1.3.2_all.ipk, and for qmi modem additionally 3ginfo-qmisignal_20171227_all.ipk.
