### ISSUE TITLE
hilink modem not working

### ISSUE THREAD

**Issue by kyliezero** [4IceG/luci-app-3ginfo#5]
the modem I use is e3372 hilink, how do I get it to work

`#Interfaces`
![Screenshot_2021-11-06_12-01-54](https://user-images.githubusercontent.com/87708571/140598706-84300c3b-b7a5-4976-9e46-ff7bd6b795dc.png)

`#Configuration 3ginfo`
![Screenshot_2021-11-06_12-02-19](https://user-images.githubusercontent.com/87708571/140598728-9c2279af-39bd-4ec5-916c-d642cf5c5422.png)

`#Information about 3G/4G connection`
![Screenshot_2021-11-06_12-02-51](https://user-images.githubusercontent.com/87708571/140598740-96048565-eb21-48c4-912f-e3be0d75a42b.png)

**OpenWrt R2021.11.04 / LuCI Master (git-21.280.14233-9b796b1) **

**Comment by 4IceG** [comment]
Hi, do you have the wget-nossl package installed? What does the command
"usr/share/3ginfo/scripts/huawei_hilink.sh 192.168.8.1 debug"  show?

sob., 6 lis 2021, 06:11 użytkownik kyliezero ***@***.***>
napisał:

**Comment by kyliezero** [comment]
package wget-nossl already installed
![uiuii](https://user-images.githubusercontent.com/87708571/140599606-12cb4b50-5704-46fd-b782-a8856f2db1ec.png)
![Screenshot_2021-11-06_12-56-31](https://user-images.githubusercontent.com/87708571/140599638-5f94d99e-9f29-4f6e-b2b1-60ba6f7e701d.png)

**Comment by 4IceG** [comment]
I am not surprised that my 3ginfo frontend does not work, as 3ginfo itself
does not get any information from the modem. Try to convert hilink to wan,
remove wget-ssl. If nothing moves, please report the bug to Cezary (
https://github.com/obsy/packages/tree/master/3ginfo), he is the maintainer
of the package, maybe he will know why nothing is happening.

sob., 6 lis 2021, 06:57 użytkownik kyliezero ***@***.***>
napisał:

**Comment by kyliezero** [comment]
I tried to reinstall wget-nossl, and I tried again the command `usr/share/3ginfo/scripts/huawei_hilink.sh 192.168.8.1 debug` and the result
![Screenshot_2021-11-06_13-14-31](https://user-images.githubusercontent.com/87708571/140600042-0178e343-ab48-43b9-8a6d-1c80889e6cde.png)

but in luci still nothing is shown
![Screenshot_2021-11-06_13-18-52](https://user-images.githubusercontent.com/87708571/140600063-919b45ab-57ca-40b1-ab03-4519acc71818.png)

**Comment by kyliezero** [comment]
command `3ginfo` works, but in luci-app nothing is showing
![Screenshot_2021-11-06_13-21-48](https://user-images.githubusercontent.com/87708571/140600163-672ea3b8-250f-47c4-8504-1774e442c781.png)

**Comment by 4IceG** [comment]
Ok, so 3ginfo is already downloading information. Run the command
"/etc/init.d/3ginfo start". My package should work too. Try to restart the
router after executing the command, let it refresh.

sob., 6 lis 2021, 07:24 użytkownik kyliezero ***@***.***>
napisał:

**Comment by kyliezero** [comment]
root@LYNX:~# /etc/init.d/3ginfo start
-bash: /etc/init.d/3ginfo: No such file or directory

**Comment by 4IceG** [comment]
Ok, I'm going to run 3ginfo on my own router and look, it must work, I have
never had problems with the package.

sob., 6 lis 2021, 07:35 użytkownik kyliezero ***@***.***>
napisał:

**Comment by kyliezero** [comment]
I try to access http://192.168.1.1:81 it works, but in luci-app no data is displayed
![Screenshot_2021-11-06_13-58-09](https://user-images.githubusercontent.com/87708571/140601105-b253b9af-e202-40e8-9907-426b18f72a72.png)

**Comment by 4IceG** [comment]
I checked a moment ago and everything shows beautifully. Just change the settings from hilink to HILINK.

![hilink](https://user-images.githubusercontent.com/59826889/140602228-058eee35-72da-49ec-a856-c43d3beb7c19.PNG)
.
