### ISSUE TITLE
Status show's Disconnected

### ISSUE THREAD

**Issue by Josephur** [4IceG/luci-app-3ginfo#6]
Got this installed on LTEFix's GoldenOrb firmware, and it seems to provide some information sometimes, other times much of the information is missing or empty, and it never shows the Status as Connected, always DISCONNECTED.  Connection time is also always blank, as is Operator.  

The only thing that consistently seems to show is MCC,CSQ,LAC,CID,TAC.

I'm using LTEFix's NEXQ6GO router with an EM7411 in QMI mode.

What can I try to fix this?

![image](https://user-images.githubusercontent.com/6666442/147381863-a157962e-34ce-4a26-8476-ca8ba8421bbd.png)

**Comment by 4IceG** [comment]
Hi. The 3ginfo package doesn't show many things for two reasons. The first
is that the package is old and does not support newer modems, the second is
the system it was installed on. It cannot be very modified and other
packages cannot communicate with the modem. Install the package
https://github.com/koshev-msk/luci-app-modeminfo if it succeeds .. it might
show more data.

sob., 25 gru 2021, 10:06 użytkownik Josephur ***@***.***>
napisał:

**Comment by 4IceG** [comment]
Returning to the "Disconnected" message, probably the name "WAN" in the settings does not match.
