### ISSUE TITLE
OpenWrt 21.02.0-rc4 r16256-2d5ee43dc6

### ISSUE THREAD

**Issue by thytum** [4IceG/luci-app-3ginfo#7]
Hi from brazil :D, 
Thanks for the code, however it seems not to work on luci in  OpenWrt 21.02.0-rc4 r16256-2d5ee43dc6 version, what i should do to make it work ?

root@OpenWrt:~# opkg install 3ginfo
3ginfo-qmisignal_20190418_all.ipk  3ginfo-text_20190418_all.ipk       3ginfo_20190418_all.ipk
root@OpenWrt:~# opkg install 3ginfo-qmisignal_20190418_all.ipk 3ginfo-text_20190418_all.ipk
Installing 3ginfo-qmisignal (20190418) to root...
Installing 3ginfo-text (20190418) to root...
Configuring 3ginfo-qmisignal.
Configuring 3ginfo-text.
ln: /usr/bin/3ginfo: File exists
root@OpenWrt:~# opkg install 3ginfo_20190418_all.ipk
Installing 3ginfo (20190418) to root...
Configuring 3ginfo.
root@OpenWrt:~# reboot

root@OpenWrt:~# 3ginfo
Status: Rozłączony
Czas polaczenia: -
Przeslano danych: - / -
Operator: -
Tryb pracy: UMTS
Sila sygnalu: 32%
Urzadzenie: TCT Mobile International Limited HSPA Data Card
MCC MNC: 724 02
LAC: CD35 (52533)
CID: C2BD194 (204198292)
TAC: - (-)
CSQ: 10
RSSI: -93 dBm
RSCP: - dBm
Ec/IO: - dB
RSRP: - dBm
SINR: - dB
RSRQ: - dB

**Comment by thytum** [comment]
sorry, all solved with instalation of [luci-app-3ginfo_1.3.3_all.ipk](https://github.com/4IceG/luci-app-3ginfo/releases/download/1.3.3/luci-app-3ginfo_1.3.3_all.ipk)  and it works like a charm :D 
![image](https://user-images.githubusercontent.com/75786137/160978063-d8f9d4b1-25d5-486f-a710-fc3fad4add92.png)

dzięki maaa friend!!!!!

**Comment by 4IceG** [comment]
Hi,
Greetings from Poland :)
I'm glad it works, although the modem as for me exotic.

You can try swapping the contents of the file in the router
/usr/share/3ginfo/mccmnc.dat

to the content of this file
https://github.com/4IceG/luci-app-3ginfo-lite/blob/main/luci-app-3ginfo-lite/root/usr/share/3ginfo-lite/mccmnc.dat

Maybe then 3ginfo will show the operator name.

**Comment by thytum** [comment]
Working like a charm! btw its a old old ollllllld modem alcatel x090s, im looking for a simple 4.5g usd dongle modem can you advise me some ? man please put 3ginfo at openwrt opkg repository it works so well!! dzięki dzięki !
![image](https://user-images.githubusercontent.com/75786137/161065162-91fb601e-2457-475b-9e95-254e93338274.png)

**Comment by 4IceG** [comment]
Question.. what do you mean "4.5g usb dongle modem", another how much money do you want to spend on the modem, can you use an external antenna.

I also don't know what modems are available in Brazil :).

**Comment by thytum** [comment]
antenna is a good point as im doing it for a rural zone, we grow some beef cattle in here for make hamburgers later haha, uhm i was about to look some in aliexpress but all i found was those with wifi ready like 2in1, do you think it will work on openwrt ?

**Comment by 4IceG** [comment]
MiFi modems/routers are a bad idea, they have band aggregation and are quite cheap, but for OpenWrt I advise against.
Modems on usb are not produced any more so if you want to do it you need m2 modem + USB adapter + external antenna.

Take a look at my packages, there are supported modems listed. In the past I would recommend for example Quectel EM12-G.
Before choosing a modem you need to know the bands supported in Brazil in order not to buy something that will not work.

**Comment by thytum** [comment]
found it https://www.ebay.com/itm/383450539386?_ul=MX&chn=ps&norover=1&mkevt=1&mkrid=21527-161791-684379-7&mkcid=2&itemid=383450539386&targetid=1599203563417&device=c&mktype=pla&googleloc=9101149&poi=&campaignid=13433240304&mkgroupid=125796657480&rlsatarget=pla-1599203563417&abcId=9300584&merchantid=118952506&gclid=CjwKCAjwopWSBhB6EiwAjxmqDd5lPbja_wjRDcaF_XdN2JjxHdZaeM4l2cTkCgnv4zCJgEvxmu4RqBoChvgQAvD_BwE  thank you very much!!! it will works.
