### ISSUE TITLE
Huawei B312-926

### ISSUE THREAD

**Issue by adisubagja** [4IceG/luci-app-3ginfo#8]
![Screenshot (2)](https://user-images.githubusercontent.com/15952175/162957634-d25e181c-cbae-4bcf-8975-0bb2c7ba18cb.png)

This cannot show ?
Not support or why

**Comment by 4IceG** [comment]
Hi, it's hard for me to say why it doesn't work. I do not know this router
/ modem, so I do not know if it is possible to communicate with it, whether
via Hi-Link or via the diagnostic port.

wt., 12 kwi 2022, 13:58 użytkownik Adi Subagja ***@***.***>
napisał:

**Comment by adisubagja** [comment]
![Screenshot_20220413-112646370](https://user-images.githubusercontent.com/15952175/163100160-bfa1bfb6-6706-4a17-b1e1-7e695943cdb1.jpg)

Ok np.
but i have reference here this can show info using apk huawei manager

im using on huawei manager no password this cannot show info and then i tried using password admin login this show info

I think luci-app-3ginfo needed feature a login admin page for getting more result for my modem

Thanks for answer before

**Comment by 4IceG** [comment]
I doubt it will work, but you could try installing the wget-nossl package, then under "Configuration" the "Device" field, enter the router/modem address 192.168.8.1? and see if it returns anything.
